#!/usr/bin/env node
/* build.mjs — dev tool (Node >= 18, no deps).
   Assembles the whole static site:
     src/es/<page>.html  -> <page>.html            (Spanish, site root)
     src/en/<page>.html  -> en/<page>.html         (English)
     templates/listing.<lang>.html + data/listings.json
                         -> inmuebles/<slug>.html and en/properties/<slug>.html
     sitemap.xml with hreflang alternates.
   Each page source starts with a JSON comment:
     <!--@page {"title":"…","desc":"…","nav":"home","alt":"en/index.html"}-->
   Partials live in templates/partials/<lang>/{head,header,footer}.html.
   Tokens: {{ROOT}} relative prefix to the site root, {{NAV_<key>}} current-page
   marker, {{SELF_URL}}/{{ALT_URL}} language switch, plus data-driven blocks
   ({{FEATURED_SHOWCASE}}, {{LISTING_CARDS}}, {{ZONE_OPTIONS}}, {{TYPE_OPTIONS}}). */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const SITE = "https://www.inmobiliariagrande.com";
const LANGS = ["es", "en"];
const LISTING_DIR = { es: "inmuebles", en: "en/properties" };

/* ------------------------------------------------------------------ utils */
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const escAttr = (s) => esc(s).replace(/"/g, "&quot;");
const nf = { es: new Intl.NumberFormat("es-ES", { maximumFractionDigits: 0 }), en: new Intl.NumberFormat("en-GB", { maximumFractionDigits: 0 }) };
const nfDec = { es: new Intl.NumberFormat("es-ES", { maximumFractionDigits: 2 }), en: new Intl.NumberFormat("en-GB", { maximumFractionDigits: 2 }) };
const fmtInt = (n, lang) => nf[lang].format(n);
const fmtDec = (n, lang) => nfDec[lang].format(n);
const EMOJI = /\p{Extended_Pictographic}/gu;

function fail(message) {
  console.error(`build: ${message}`);
  process.exit(1);
}
function read(rel) {
  const p = path.join(ROOT, rel);
  if (!existsSync(p)) fail(`missing file ${rel}`);
  return readFileSync(p, "utf8");
}
function write(rel, content) {
  const p = path.join(ROOT, rel);
  mkdirSync(path.dirname(p), { recursive: true });
  writeFileSync(p, content);
  console.log(`wrote ${rel}`);
}
function render(tpl, tokens) {
  let html = tpl;
  for (const [key, value] of Object.entries(tokens)) html = html.split(`{{${key}}}`).join(value);
  const left = html.match(/\{\{[A-Z_a-z0-9]+\}\}/g);
  if (left) fail(`unreplaced tokens: ${[...new Set(left)].join(", ")}`);
  return html;
}
/* Relative prefix from an output file back to the site root. */
function rootPrefix(outRel) {
  const depth = outRel.split("/").length - 1;
  return depth ? "../".repeat(depth) : "";
}
function cleanText(s) {
  return String(s).replace(EMOJI, "").replace(/!(\p{L})/gu, "¡$1").replace(/\s+/g, " ").trim();
}

/* ------------------------------------------------------------------ data */
const listings = JSON.parse(read("data/listings.json"));
const i18n = JSON.parse(read("data/i18n.json"));
if (!Array.isArray(listings)) fail("data/listings.json must be an array");

function typeName(listing, lang) {
  if (lang === "es") return listing.type;
  return i18n.types[listing.type] || listing.type;
}
function listingTitle(listing, lang) {
  if (lang === "es") return listing.title;
  const t = i18n.listings[listing.id];
  return (t && t.title) || `${typeName(listing, "en")} in ${listing.zone}, ${listing.city}`;
}
/* Some scraped headlines are CRM leftovers ("en la localidad de"); drop anything that short. */
function listingHeadline(listing, lang) {
  if (lang === "es") {
    const h = cleanText(listing.headline || "");
    if (h.length < 15 || /\b(de|en|la|el)$/i.test(h)) return "";
    return h.charAt(0).toUpperCase() + h.slice(1);
  }
  const t = i18n.listings[listing.id];
  return (t && t.headline) || "";
}
function headlineP(listing, lang) {
  const h = listingHeadline(listing, lang);
  return h ? `<p style="margin:0;color:var(--lilac-light);">${esc(h)}</p>` : "";
}
function listingUrl(listing, lang) {
  return `${LISTING_DIR[lang]}/${listing.slug}.html`;
}
function priceText(listing, lang) {
  const base = `${fmtInt(listing.price, lang)} €`;
  return listing.operation === "alquiler" ? `${base}${i18n.ui[lang].per_month.replace("€", "")}` : base;
}
function opLabel(listing, lang) {
  const o = i18n.operations[listing.operation];
  return o ? o[lang] : listing.operation;
}
function specs(listing, lang) {
  const ui = i18n.ui[lang];
  const baths = listing.baths === 1 ? ui.baths_1 : ui.baths_n;
  return [`${fmtInt(listing.surface_built_m2, lang)} m²`, `${listing.rooms} ${ui.rooms}`, `${listing.baths} ${baths}`];
}

/* Every source photo has a sibling .webp (generated by `magick … -quality 78`,
   see README). <picture> serves it first, JPEG stays as the universal fallback. */
const webpOf = (p) => p.replace(/\.jpg$/i, ".webp");
/* 1024px-wide mid variant, quality 72 (see README) — the full 1400w webp is
   reserved for large screens so a phone on a slow link isn't served it. */
const midWebpOf = (p) => p.replace(/\.jpg$/i, "-m.webp");
/* 240px-wide variant of the *thumb* (…-s.jpg -> …-t.webp), quality 68 — for the
   gallery thumbnail strip, shown at ~100–200px, where the 640w thumb is overkill. */
const tinyWebpOf = (p) => p.replace(/-s\.jpg$/i, "-t.webp");

const ICON_HEART = '<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M12 21s-7.5-4.6-9.6-9.3C.9 8.3 3 5 6.4 5c2 0 3.4 1.1 4.1 2.3h3C14.2 6.1 15.6 5 17.6 5 21 5 23.1 8.3 21.6 11.7 19.5 16.4 12 21 12 21z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg>';
const ICON_X = '<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M6 6l12 12M18 6L6 18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>';

function cardActions(listing, lang) {
  const ui = i18n.ui[lang];
  return `<div class="card__actions">
        <button class="icon-btn" type="button" data-fav="${escAttr(listing.id)}" aria-pressed="false" aria-label="${escAttr(ui.save)}">${ICON_HEART}</button>
        <button class="icon-btn icon-btn--dismiss" type="button" data-dismiss="${escAttr(listing.id)}" aria-pressed="false" aria-label="${escAttr(ui.dismiss)}">${ICON_X}</button>
      </div>`;
}
function badge(listing, lang) {
  const ui = i18n.ui[lang];
  if (listing.status === "reservado") return `<span class="badge badge--reserved">${esc(ui.reserved)}</span>`;
  if (listing.operation === "alquiler") return `<span class="badge badge--rent">${esc(opLabel(listing, lang))}</span>`;
  return `<span class="badge">${esc(opLabel(listing, lang))}</span>`;
}
function dataAttrs(listing) {
  const feats = (listing.features || []).join("|");
  return `data-id="${escAttr(listing.id)}" data-type="${escAttr(listing.type)}" data-zone="${escAttr(listing.zone)}" data-city="${escAttr(listing.city)}" data-op="${escAttr(listing.operation)}" data-price="${listing.price}" data-rooms="${listing.rooms}" data-baths="${listing.baths}" data-m2="${listing.surface_built_m2}" data-date="${escAttr(listing.source_fetched_at || "")}" data-features="${escAttr(feats)}"`;
}

/* Standard listing card (grid of 4 on the home, results on the listing page). */
function card(listing, lang, root, opts = {}) {
  const ui = i18n.ui[lang];
  const p = listing.photos[0];
  const url = root + listingUrl(listing, lang);
  const sp = specs(listing, lang).map((s) => `<li>${s}</li>`).join("");
  const eager = opts.eager ? "" : ' loading="lazy" decoding="async"';
  return `<article class="card" ${dataAttrs(listing)}>
      ${badge(listing, lang)}
      ${cardActions(listing, lang)}
      <a class="card__link" href="${escAttr(url)}">
        <div class="card__media"><picture><source srcset="${root}${escAttr(webpOf(p.thumb))}" type="image/webp"><img src="${root}${escAttr(p.thumb)}" alt="${escAttr(p.alt)}" width="640" height="426"${eager}></picture></div>
        <div class="card__body">
          <p class="card__place">${esc(listing.zone)} · ${esc(listing.city)}</p>
          <h3 class="card__title">${esc(listingTitle(listing, lang))}</h3>
          <ul class="card__specs">${sp}</ul>
          <p class="card__price">${priceText(listing, lang)}</p>
        </div>
      </a>
    </article>`;
}
function featureCard(listing, lang, root) {
  const p = listing.photos[0];
  const url = root + listingUrl(listing, lang);
  const sp = specs(listing, lang).map((s) => `<li>${s}</li>`).join("");
  return `<a class="feature-card" href="${escAttr(url)}" ${dataAttrs(listing)}>
        <picture>
          <source srcset="${root}${escAttr(webpOf(p.thumb))} 640w, ${root}${escAttr(midWebpOf(p.src))} 1024w, ${root}${escAttr(webpOf(p.src))} 1400w" sizes="(max-width: 960px) 100vw, 60vw" type="image/webp">
          <img class="feature-card__img" src="${root}${escAttr(p.src)}" srcset="${root}${escAttr(p.thumb)} 640w, ${root}${escAttr(p.src)} 1400w" sizes="(max-width: 960px) 100vw, 60vw" alt="${escAttr(p.alt)}" width="1400" height="933" fetchpriority="high">
        </picture>
        <span class="feature-card__veil" aria-hidden="true"></span>
        ${badge(listing, lang)}
        <span class="feature-card__body">
          <span>
            <span class="feature-card__place">${esc(listing.zone)} · ${esc(listing.city)}</span>
            <h3>${esc(listingTitle(listing, lang))}</h3>
            <ul class="feature-card__specs">${sp}</ul>
          </span>
          <strong class="feature-card__price">${priceText(listing, lang)}</strong>
        </span>
      </a>`;
}
function sideCard(listing, lang, root) {
  const p = listing.photos[0];
  const url = root + listingUrl(listing, lang);
  const sp = specs(listing, lang).map((s) => `<li>${s}</li>`).join("");
  return `<a class="side-card" href="${escAttr(url)}" ${dataAttrs(listing)}>
        <span class="side-card__media">${badge(listing, lang)}<picture><source srcset="${root}${escAttr(webpOf(p.thumb))}" type="image/webp"><img src="${root}${escAttr(p.thumb)}" alt="${escAttr(p.alt)}" width="640" height="426" loading="lazy" decoding="async"></picture></span>
        <span class="side-card__body">
          <span class="card__place">${esc(listing.zone)} · ${esc(listing.city)}</span>
          <h3>${esc(listingTitle(listing, lang))}</h3>
          <ul class="card__specs">${sp}</ul>
          <strong class="side-card__price">${priceText(listing, lang)}</strong>
        </span>
      </a>`;
}
/* Home showcase: 1 feature + 2 side cards + a row of 4. Order: most expensive first
   so the feature slot shows the flagship; reserved listings go last. */
function showcase(lang, root) {
  const sorted = listings
    .slice()
    .sort((a, b) => (a.status === "reservado") - (b.status === "reservado") || b.price - a.price);
  const [f, s1, s2, ...rest] = sorted;
  const row = rest.slice(0, 4).map((l) => card(l, lang, root)).join("\n");
  return `<div class="showcase">
      ${featureCard(f, lang, root)}
      <div class="showcase__side">
        ${sideCard(s1, lang, root)}
        ${sideCard(s2, lang, root)}
      </div>
    </div>
    <div class="grid-4">
      ${row}
    </div>`;
}
function listingCards(lang, root) {
  return listings.map((l) => card(l, lang, root)).join("\n");
}
function zoneOptions(lang) {
  const all = lang === "es" ? "Toda la provincia" : "Whole province";
  const capital = lang === "es" ? "Granada capital" : "Granada city";
  const zones = new Set();
  for (const l of listings) for (const z of [l.zone, l.city]) if (z !== "Granada") zones.add(z);
  const sorted = [...zones].sort((a, b) => a.localeCompare(b, "es"));
  return [`<option value="">${all}</option>`, `<option value="Granada capital">${capital}</option>`]
    .concat(sorted.map((z) => `<option value="${escAttr(z)}">${esc(z)}</option>`))
    .join("\n");
}
/* Home map: one label per listing, positioned by data/geo.json (approximate). */
const geo = JSON.parse(read("data/geo.json"));
function mapData(lang, root) {
  const rows = listings
    .filter((l) => geo[l.id])
    .map((l) => ({
      id: l.id,
      title: listingTitle(l, lang),
      price: priceText(l, lang),
      url: root + listingUrl(l, lang),
      lat: geo[l.id].lat,
      lng: geo[l.id].lng,
      reserved: l.status === "reservado",
    }));
  return JSON.stringify(rows).replace(/</g, "\\u003c");
}
function mapList(lang, root) {
  return listings
    .filter((l) => geo[l.id])
    .map((l) => `<li><a href="${root}${escAttr(listingUrl(l, lang))}">${esc(listingTitle(l, lang))} · ${priceText(l, lang)}</a></li>`)
    .join("");
}
function typeOptions(lang) {
  const all = lang === "es" ? "Todos los tipos" : "All types";
  const present = [...new Set(listings.map((l) => l.type))];
  const extra = ["Local", "Garaje", "Terreno"].filter((t) => !present.includes(t));
  return [`<option value="">${all}</option>`]
    .concat([...present, ...extra].map((t) => `<option value="${escAttr(t)}">${esc(typeName({ type: t }, lang))}</option>`))
    .join("\n");
}

/* --------------------------------------------------------------- pages */
function parsePage(src, file) {
  const m = src.match(/^<!--@page\s+(\{[\s\S]*?\})\s*-->\s*/);
  if (!m) fail(`${file}: missing <!--@page {...}--> header`);
  let meta;
  try { meta = JSON.parse(m[1]); } catch (e) { fail(`${file}: invalid page JSON (${e.message})`); }
  for (const k of ["title", "desc", "nav", "alt"]) if (meta[k] == null) fail(`${file}: page header lacks "${k}"`);
  return { meta, body: src.slice(m[0].length) };
}
const NAV_KEYS = ["home", "comprar", "alquilar", "locales", "vender", "casa", "contacto"];
function navTokens(active) {
  const t = {};
  for (const k of NAV_KEYS) t[`NAV_${k}`] = k === active ? ' aria-current="page"' : "";
  return t;
}
function wrap(lang, outRel, meta, body, extra = {}) {
  const root = rootPrefix(outRel);
  const altRel = meta.alt;
  const es = lang === "es" ? outRel : altRel;
  const en = lang === "en" ? outRel : altRel;
  const tokens = {
    ROOT: root,
    PAGE_TITLE: escAttr(meta.title),
    META_DESC: escAttr(meta.desc),
    CANONICAL: `${SITE}/${outRel}`,
    HREFLANG_ES: `${SITE}/${es}`,
    HREFLANG_EN: `${SITE}/${en}`,
    OG_IMAGE: meta.og ? `${SITE}/${meta.og}` : `${SITE}/assets/brand/icon-512.png`,
    EXTRA_HEAD: (meta.extraHead || "").split("{{ROOT}}").join(root),
    HEADER_CLASS: meta.nav === "home" ? "site-header--overlay" : "",
    SELF_URL: root + outRel,
    ALT_URL: root + altRel,
    ...navTokens(meta.nav),
    ...extra,
  };
  const head = read(`templates/partials/${lang}/head.html`);
  const header = read(`templates/partials/${lang}/header.html`);
  const footer = read(`templates/partials/${lang}/footer.html`);
  return render(head + header + body + footer, tokens);
}
function buildPages(lang) {
  const dir = path.join(ROOT, "src", lang);
  if (!existsSync(dir)) return [];
  const out = [];
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".html"))) {
    const src = readFileSync(path.join(dir, file), "utf8");
    const { meta, body } = parsePage(src, `src/${lang}/${file}`);
    const outRel = lang === "es" ? file : `en/${file}`;
    const root = rootPrefix(outRel);
    const html = wrap(lang, outRel, meta, body, {
      FEATURED_SHOWCASE: showcase(lang, root),
      LISTING_CARDS: listingCards(lang, root),
      ZONE_OPTIONS: zoneOptions(lang),
      TYPE_OPTIONS: typeOptions(lang),
      LISTING_COUNT: String(listings.length),
      MAP_DATA: mapData(lang, root),
      MAP_LIST: mapList(lang, root),
    });
    write(outRel, html);
    if (!meta.noindex) out.push({ es: lang === "es" ? outRel : meta.alt, en: lang === "en" ? outRel : meta.alt, self: outRel });
  }
  return out;
}

/* ------------------------------------------------------------ listings */
const LEGAL_PREFIXES = ["AVISO IMPORTANTE", "De conformidad", "IMPUESTOS A CARGO", "NOTARIA Y REGISTRO", "HONORARIOS PROFESIONALES", "EN EL CASO DE PRECISAR", "PARA EL CÁLCULO", "El precio indicado no incluye"];
function splitDescription(listing) {
  const main = [], legal = [];
  for (const raw of listing.description || []) {
    const p = cleanText(raw);
    if (!p) continue;
    (LEGAL_PREFIXES.some((x) => p.startsWith(x)) ? legal : main).push(p);
  }
  return { main, legal };
}
function galleryHtml(listing, lang, root) {
  const ui = i18n.ui[lang];
  const total = listing.photos.length;
  const main = listing.photos[0];
  const thumbs = listing.photos
    .map((p, i) => `<li><a href="${root}${escAttr(p.src)}"${i === 0 ? ' aria-current="true"' : ""} aria-label="${lang === "es" ? `Ver fotografía ${i + 1} de ${total}` : `View photo ${i + 1} of ${total}`}"><picture><source srcset="${root}${escAttr(tinyWebpOf(p.thumb))}" type="image/webp"><img src="${root}${escAttr(p.thumb)}" alt="${escAttr(p.alt)}" width="640" height="426" loading="lazy" decoding="async"></picture></a></li>`)
    .join("\n        ");
  const note = lang === "es"
    ? `Fotografías de la vivienda. En la oficina tenemos el reportaje completo (${esc(listing.photo_count_on_source)} fotos).`
    : `Photos of the property. The full set (${esc(listing.photo_count_on_source)} photos) is available at the office.`;
  return `<figure class="gallery">
      <picture>
        <source srcset="${root}${escAttr(webpOf(main.thumb))} 640w, ${root}${escAttr(midWebpOf(main.src))} 1024w, ${root}${escAttr(webpOf(main.src))} 1400w" sizes="(max-width: 640px) 100vw, 1320px" type="image/webp">
        <img class="gallery__main" src="${root}${escAttr(main.src)}" srcset="${root}${escAttr(main.thumb)} 640w, ${root}${escAttr(main.src)} 1400w" sizes="(max-width: 640px) 100vw, 1320px" alt="${escAttr(main.alt)}" width="1400" height="933" fetchpriority="high">
      </picture>
      <ul class="gallery__thumbs">
        ${thumbs}
      </ul>
      <figcaption class="gallery__note">${note}</figcaption>
    </figure>`;
}
const FIG = {
  es: { built: "Superficie construida", useful: "Superficie útil", rooms: "Dormitorios", baths: "Baños", cond: "Estado", plot: "Parcela", year: "Año", ref: "Referencia" },
  en: { built: "Built area", useful: "Usable area", rooms: "Bedrooms", baths: "Bathrooms", cond: "Condition", plot: "Plot", year: "Year built", ref: "Reference" },
};
function figuresHtml(listing, lang) {
  const L = FIG[lang];
  const item = (label, value) => `<div class="figures__item"><span class="figures__label">${label}</span><span class="figures__value">${value}</span></div>`;
  const out = [item(L.built, `${fmtInt(listing.surface_built_m2, lang)} m²`)];
  if (listing.surface_useful_m2 != null) out.push(item(L.useful, `${fmtInt(listing.surface_useful_m2, lang)} m²`));
  out.push(item(L.rooms, String(listing.rooms)), item(L.baths, String(listing.baths)), item(L.cond, esc(listing.condition)));
  if (listing.plot_m2 != null) out.push(item(L.plot, `${fmtInt(listing.plot_m2, lang)} m²`));
  if (listing.year_built != null) out.push(item(L.year, String(listing.year_built)));
  out.push(item(L.ref, esc(listing.ref)));
  return out.join("\n        ");
}
function energyHtml(listing, lang) {
  const e = listing.energy;
  if (!e || e.consumption_kwh_m2_year == null || e.emissions_kg_co2_m2_year == null) return "";
  const t = lang === "es" ? ["Certificado energético", "Consumo", "Emisiones"] : ["Energy certificate", "Consumption", "Emissions"];
  return `<section>
            <h2>${t[0]}</h2>
            <div class="energy__grid">
              <div class="energy__box"><p class="energy__label">${t[1]}</p><p class="energy__value">${fmtDec(e.consumption_kwh_m2_year, lang)} kWh/m² ${lang === "es" ? "año" : "year"}</p></div>
              <div class="energy__box"><p class="energy__label">${t[2]}</p><p class="energy__value">${fmtDec(e.emissions_kg_co2_m2_year, lang)} kg CO₂/m² ${lang === "es" ? "año" : "year"}</p></div>
            </div>
          </section>`;
}
function descriptionHtml(listing, lang) {
  const { main, legal } = splitDescription(listing);
  const body = main.map((p) => `<p>${esc(p)}</p>`).join("\n            ");
  let note = "";
  if (legal.length) {
    const summary = lang === "es" ? "Gastos e impuestos no incluidos en el precio" : "Costs and taxes not included in the price (Spanish)";
    note = `<details class="legal-note" lang="es"><summary>${summary}</summary>${legal.map((p) => `<p>${esc(p)}</p>`).join("")}</details>`;
  }
  return { body, note, first: main[0] || "" };
}
function jsonLd(listing, desc, pageUrl) {
  const data = {
    "@context": "https://schema.org",
    "@type": "RealEstateListing",
    name: listing.title,
    url: pageUrl,
    description: desc,
    image: listing.photos.map((p) => `${SITE}/${p.src}`),
    numberOfRooms: listing.rooms,
    numberOfBathroomsTotal: listing.baths,
    floorSize: { "@type": "QuantitativeValue", value: listing.surface_built_m2, unitCode: "MTK" },
    address: { "@type": "PostalAddress", addressLocality: listing.city, addressRegion: "Granada", addressCountry: "ES" },
    offers: {
      "@type": "Offer", price: listing.price, priceCurrency: "EUR",
      availability: listing.status === "reservado" ? "https://schema.org/LimitedAvailability" : "https://schema.org/InStock",
      seller: { "@type": "RealEstateAgent", name: "Inmobiliaria Grande", url: `${SITE}/index.html`, telephone: "+34958252461" },
    },
  };
  return `<script type="application/ld+json">\n${JSON.stringify(data, null, 2)}\n</script>`;
}
function buildListing(listing, lang) {
  const outRel = listingUrl(listing, lang);
  const root = rootPrefix(outRel);
  const pageUrl = `${SITE}/${outRel}`;
  const { body, note, first } = descriptionHtml(listing, lang);
  const sp = specs(listing, lang);
  const title = lang === "es"
    ? `${listing.type} en ${listing.zone}, ${listing.city} · ${fmtInt(listing.price, "es")} € | Inmobiliaria Grande, Granada`
    : `${typeName(listing, "en")} in ${listing.zone}, ${listing.city} · €${fmtInt(listing.price, "en")} | Inmobiliaria Grande, Granada`;
  const desc = lang === "es"
    ? `${listing.type} en ${listing.zone}, ${listing.city}: ${sp.join(", ")} por ${fmtInt(listing.price, "es")} €. Ref. ${listing.ref}. Concierta tu visita con Inmobiliaria Grande, desde 1970.`
    : `${typeName(listing, "en")} in ${listing.zone}, ${listing.city}: ${sp.join(", ")} for €${fmtInt(listing.price, "en")}. Ref. ${listing.ref}. Book a viewing with Inmobiliaria Grande, since 1970.`;
  const meta = { title, desc, nav: "comprar", alt: listingUrl(listing, lang === "es" ? "en" : "es"), og: listing.photos[0].src, extraHead: jsonLd(listing, cleanText(first), pageUrl) };
  const tpl = read(`templates/listing.${lang}.html`);
  const tokens = {
    H1: esc(listingTitle(listing, lang)),
    HEADLINE: esc(listingHeadline(listing, lang)),
    HEADLINE_P: headlineP(listing, lang),
    TYPE: esc(typeName(listing, lang)),
    ZONE: esc(listing.zone), CITY: esc(listing.city), PROVINCE: esc(listing.province),
    PRICE_FMT: priceText(listing, lang), PRICE_RAW: String(listing.price),
    REF: escAttr(listing.ref), ID: escAttr(listing.id), OP: esc(opLabel(listing, lang)),
    BADGE: listing.status === "reservado" ? `<span class="badge badge--reserved">${esc(i18n.ui[lang].reserved)}</span>` : "",
    GALLERY: galleryHtml(listing, lang, root),
    FIGURES: figuresHtml(listing, lang),
    DESCRIPTION: body, LEGAL_NOTE: note,
    FEATURES: (listing.features || []).map((f) => `<li>${esc(f)}</li>`).join("\n              "),
    ENERGY: energyHtml(listing, lang),
    SPECS: sp.join(" · "),
    SHARE_URL: pageUrl,
  };
  write(outRel, wrap(lang, outRel, meta, tpl, tokens));
  return outRel;
}

/* ------------------------------------------------------------ sitemap */
function sitemapXml(entries) {
  const url = (e) => `  <url>
    <loc>${SITE}/${e.self}</loc>
    <xhtml:link rel="alternate" hreflang="es" href="${SITE}/${e.es}"/>
    <xhtml:link rel="alternate" hreflang="en" href="${SITE}/${e.en}"/>
  </url>`;
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${entries.map(url).join("\n")}
</urlset>
`;
}

/* ---------------------------------------------------------------- main */
function main() {
  for (const listing of listings) {
    for (const key of ["id", "slug", "title", "price", "ref", "photos"]) {
      if (listing[key] == null) fail(`listing missing "${key}" (${listing.id || "?"})`);
    }
    if (!listing.photos.length) fail(`listing ${listing.id} has no photos`);
    for (const photo of listing.photos) {
      for (const file of [photo.src, photo.thumb]) if (!existsSync(path.join(ROOT, file))) fail(`missing photo ${file}`);
      if (!photo.alt) fail(`listing ${listing.id}: photo ${photo.src} has empty alt`);
    }
  }
  const entries = [];
  for (const lang of LANGS) entries.push(...buildPages(lang));
  for (const listing of listings) {
    const es = buildListing(listing, "es");
    const en = buildListing(listing, "en");
    entries.push({ self: es, es, en }, { self: en, es, en });
  }
  const seen = new Set();
  const unique = entries.filter((e) => !seen.has(e.self) && seen.add(e.self) && !/404\.html$|gracias\.html$|thanks\.html$/.test(e.self));
  write("sitemap.xml", sitemapXml(unique));
}
main();
